### ISSUE TITLE
Google Java Format 대신에 IntelliJ Format 쓰는건 어떨까요?

### ISSUE THREAD

**Issue by bloomspes** [CodeSoom/DDD-Kurly-Clone-Product#22]
빈 클래스일 때 접히거나, 인텐트도 기존 인텔리제이 인텐트 방식이 가독성이 더 깔끔한 것 같아요.
의견 주세요.

**Comment by jxmen** [comment]
https://github.com/CodeSoom/DDD-Kurly-Clone-Product/commit/c34878ba4f96f4dcfca1d47755727492983524ca 이런... 한줄에 한 점만 쓰게 작성하여도 접혀지는군요
저희가 알고 있는 포맷 방식과 조금 다른 것 같습니다.
github actions의 포매터를 그냥 삭제하고, 커밋 올리기 전에 포매터만 각자 돌리는 방식으로 하는건 어떨까요?

**Comment by bloomspes** [comment]
괜찮은 것 같습니다. :) 인텔리제이 포맷팅 추천...!

**Comment by mikekang47** [comment]
저도 같은 생각입니다! 구글포맷 인덴트가 적응이 잘 안되더라고요...!

**Comment by bloomspes** [comment]
@sunggyupaik @juunini 의견은 어떠신가요?

**Comment by juunini** [comment]
찬성

**Comment by sunggyupaik** [comment]
찬성222

**Comment by bloomspes** [comment]
그럼 ci에서 java formatter는 걷어내겠습니다.
